services:
  - type: web
    name: strideiq
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: STRAVA_FETCH_PAGES
        value: "3"
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: STRAVA_REDIRECT_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
